const STORAGE_KEY = 'celltech-dados-v1';

const dadosIniciais = {
  produtos: [
    { id: 1, nome: 'iPhone 15 Pro', marca: 'Apple', modelo: 'A2848', armazenamento: '256 GB', cor: 'Titânio Natural', preco: 7299.90, estoque: 8, emoji: '▰', tema: 'gold' },
    { id: 2, nome: 'Galaxy S24 Ultra', marca: 'Samsung', modelo: 'SM-S928B', armazenamento: '256 GB', cor: 'Cinza', preco: 6199.00, estoque: 3, emoji: '▰', tema: 'blue' },
    { id: 3, nome: 'Pixel 8 Pro', marca: 'Google', modelo: 'GC3VE', armazenamento: '128 GB', cor: 'Obsidiana', preco: 4899.00, estoque: 12, emoji: '▰', tema: 'black' },
    { id: 4, nome: 'Moto Edge 40', marca: 'Motorola', modelo: 'XT2303', armazenamento: '256 GB', cor: 'Azul', preco: 2699.90, estoque: 2, emoji: '▰', tema: 'blue' },
    { id: 5, nome: 'Redmi Note 13', marca: 'Xiaomi', modelo: '2312DRA', armazenamento: '128 GB', cor: 'Verde', preco: 1699.90, estoque: 18, emoji: '▰', tema: 'gold' }
  ],
  clientes: [
    { id: 1, nome: 'Mariana Costa', cpf: '123.456.789-00', telefone: '(11) 98888-1234', email: 'mariana@email.com', endereco: 'São Paulo, SP' },
    { id: 2, nome: 'Rafael Almeida', cpf: '987.654.321-00', telefone: '(21) 97777-4321', email: 'rafael@email.com', endereco: 'Rio de Janeiro, RJ' },
    { id: 3, nome: 'Camila Santos', cpf: '456.789.123-00', telefone: '(31) 96666-8765', email: 'camila@email.com', endereco: 'Belo Horizonte, MG' }
  ],
  vendas: [
    { id: 1001, clienteId: 1, produtoId: 1, quantidade: 1, total: 7299.90, pagamento: 'Cartão de crédito', data: '2026-10-04T14:30:00' },
    { id: 1002, clienteId: 2, produtoId: 2, quantidade: 1, total: 6199.00, pagamento: 'PIX', data: '2026-10-03T10:10:00' },
    { id: 1003, clienteId: 3, produtoId: 3, quantidade: 2, total: 9798.00, pagamento: 'Cartão de crédito', data: '2026-10-02T16:45:00' },
    { id: 1004, clienteId: 1, produtoId: 5, quantidade: 1, total: 1699.90, pagamento: 'Dinheiro', data: '2026-10-01T09:20:00' }
  ]
};

let dados = carregarDadosLocal();
let secaoAtual = 'dashboard';
let tipoModal = '';
let idEditando = null;
let carrinho = [];

function carregarDadosLocal() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(dadosIniciais); }
  catch (erro) { return structuredClone(dadosIniciais); }
}
async function carregarDadosDoBanco() {
  try {
    const resposta = await fetch('/api/state');
    if (!resposta.ok) throw new Error('API indisponível');
    dados = await resposta.json();
    localStorage.setItem(STORAGE_KEY, JSON.stringify(dados));
  } catch (erro) {
    dados = carregarDadosLocal();
  }
}
function salvarDados() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(dados));
  fetch('/api/state', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(dados) }).catch(() => {});
}
function moeda(valor) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valor); }
function dataFormatada(valor) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(valor)).replace('.', ''); }
function dataCompleta(valor) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(valor)); }
function produtoPorId(id) { return dados.produtos.find(item => item.id === Number(id)); }
function clientePorId(id) { return dados.clientes.find(item => item.id === Number(id)); }
function mostrarToast(titulo, mensagem) { document.getElementById('toastTitle').textContent = titulo; document.getElementById('toastMessage').textContent = mensagem; document.getElementById('toast').classList.add('show'); setTimeout(() => document.getElementById('toast').classList.remove('show'), 3000); }
function avatarEmoji(tema = '') { return tema ? `<div class="product-thumb ${tema}">▰</div>` : '<div class="product-thumb">▰</div>'; }
function productVisual(produto) { return `<div class="phone-visual ${produto.tema || ''}"><span>▰</span></div>`; }

function renderizar() {
  renderLoja(); renderDashboard(); renderProdutos(); renderClientes(); renderVendas(); renderEstoque(); renderRelatorios();
  document.querySelectorAll('.page-section').forEach(item => item.classList.remove('active'));
  document.getElementById(`${secaoAtual}Section`).classList.add('active');
  document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.section === secaoAtual));
  document.getElementById('pageLabel').textContent = { store: 'Loja online', dashboard: 'Dashboard', products: 'Produtos', clients: 'Clientes', sales: 'Vendas', stock: 'Estoque', reports: 'Relatórios' }[secaoAtual];
  document.getElementById('lowStockBadge').textContent = dados.produtos.filter(item => item.estoque <= 3).length;
}


function renderLoja() {
  const produtos = dados.produtos.filter(p => p.estoque > 0);
  document.getElementById('storeSection').innerHTML = `<div class="store-hero"><div class="store-hero-content"><p class="eyebrow">CELLTECH STORE</p><h1>Tecnologia que acompanha<br><em>o seu ritmo.</em></h1><p>Encontre celulares selecionados, com garantia, atendimento próximo e as melhores condições para você.</p><button class="primary-button" onclick="document.getElementById('storeCatalog').scrollIntoView({behavior:'smooth'})">Explorar celulares <span>→</span></button></div></div><div class="store-heading" id="storeCatalog"><div><p class="eyebrow">CATÁLOGO ONLINE</p><h2>Escolha seu próximo celular</h2><p>Produtos disponíveis para pronta entrega.</p></div><div class="store-actions"><div class="search-box store-search"><span>⌕</span><input placeholder="Buscar celular..." oninput="filtrarLoja(this.value)"></div><button class="cart-button" onclick="alternarCarrinho()">Carrinho <b id="cartCount">${carrinho.reduce((s,i)=>s+i.quantidade,0)}</b></button></div></div><div id="storeProducts" class="products-grid">${cardsLoja(produtos)}</div><div class="cart-drawer" id="cartDrawer"></div>`;
  atualizarCarrinho();
}
function cardsLoja(produtos) { if (!produtos.length) return '<div class="empty-state"><strong>Produto não encontrado</strong>Não temos esse modelo disponível no momento.</div>'; return produtos.map(p => `<article class="store-product-card">${productVisual(p)}<div class="store-card-content"><h3>${p.nome}</h3><p>${p.marca} · ${p.armazenamento} · ${p.cor}</p><div class="store-price-row"><strong>${moeda(p.preco)}</strong><button class="buy-button" onclick="adicionarCarrinho(${p.id})">Adicionar</button></div></div></article>`).join(''); }
function filtrarLoja(termo) { const busca = termo.toLowerCase(); document.getElementById('storeProducts').innerHTML = cardsLoja(dados.produtos.filter(p => p.estoque > 0 && `${p.nome} ${p.marca} ${p.modelo}`.toLowerCase().includes(busca))); }
function adicionarCarrinho(id) { const produto = produtoPorId(id); const item = carrinho.find(i => i.produtoId === id); const quantidadeAtual = item ? item.quantidade : 0; if (!produto || quantidadeAtual >= produto.estoque) return mostrarToast('Limite de estoque','Não há mais unidades disponíveis deste produto.'); if (item) item.quantidade += 1; else carrinho.push({produtoId:id, quantidade:1}); atualizarCarrinho(); mostrarToast('Adicionado ao carrinho', produto.nome); }
function alterarQuantidadeCarrinho(id, delta) { const item = carrinho.find(i=>i.produtoId===id); const produto = produtoPorId(id); if (!item) return; item.quantidade += delta; if (item.quantidade > (produto?.estoque || 0)) item.quantidade = produto.estoque; if (item.quantidade <= 0) carrinho = carrinho.filter(i=>i.produtoId!==id); atualizarCarrinho(); }
function atualizarCarrinho() { const drawer = document.getElementById('cartDrawer'); const count = document.getElementById('cartCount'); if (count) count.textContent = carrinho.reduce((s,i)=>s+i.quantidade,0); if (!drawer) return; const total = carrinho.reduce((s,i)=>s+(produtoPorId(i.produtoId)?.preco || 0)*i.quantidade,0); drawer.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:center"><h3>Seu carrinho</h3><button class="modal-close" onclick="alternarCarrinho()">×</button></div>${carrinho.length ? `<div class="cart-items">${carrinho.map(i=>{const p=produtoPorId(i.produtoId);return `<div class="cart-item">${avatarEmoji(p.tema)}<div class="cart-item-info"><strong>${p.nome}</strong><span>${moeda(p.preco)}</span></div><div class="cart-qty"><button onclick="alterarQuantidadeCarrinho(${p.id},-1)">−</button><b>${i.quantidade}</b><button onclick="alterarQuantidadeCarrinho(${p.id},1)">+</button></div></div>`}).join('')}</div><div class="cart-total"><span>Total</span><strong>${moeda(total)}</strong></div><button class="primary-button full" style="margin-top:14px" onclick="finalizarCompra()">Finalizar pedido <span>→</span></button>` : '<div class="empty-state"><strong>Seu carrinho está vazio</strong>Adicione um celular para continuar.</div>'}`; }
function alternarCarrinho() { const drawer = document.getElementById('cartDrawer'); if (drawer) drawer.classList.toggle('open'); }
function finalizarCompra() { if (!carrinho.length) return mostrarToast('Carrinho vazio','Adicione um produto antes de finalizar.'); const cliente = dados.clientes[0]; carrinho.forEach(item => { const p = produtoPorId(item.produtoId); p.estoque -= item.quantidade; dados.vendas.push({id:Date.now()+item.produtoId,clienteId:cliente.id,produtoId:p.id,quantidade:item.quantidade,total:p.preco*item.quantidade,pagamento:'Pedido online',data:new Date().toISOString()}); }); salvarDados(); carrinho=[]; secaoAtual='store'; renderizar(); mostrarToast('Pedido confirmado','A equipe CellTech entrará em contato para combinar a entrega.'); }

function renderDashboard() {
  const faturamento = dados.vendas.reduce((soma, venda) => soma + venda.total, 0);
  const baixos = dados.produtos.filter(item => item.estoque <= 3);
  const recentes = [...dados.vendas].sort((a,b) => new Date(b.data) - new Date(a.data)).slice(0, 4);
  document.getElementById('dashboardSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">VISÃO GERAL</p><h1>Bom dia, Alexandre.</h1><p>Acompanhe o desempenho da sua loja hoje.</p></div><button class="primary-button" onclick="abrirModal('sale')">Nova venda <span>+</span></button></div>
    <div class="stats-grid"><div class="stat-card"><div class="stat-top">Celulares cadastrados <span class="stat-icon">▣</span></div><div class="stat-value">${dados.produtos.length}</div><div class="trend"><strong>↑ 12%</strong> vs. mês passado</div></div><div class="stat-card"><div class="stat-top">Clientes ativos <span class="stat-icon">♙</span></div><div class="stat-value">${dados.clientes.length}</div><div class="trend"><strong>↑ 8%</strong> vs. mês passado</div></div><div class="stat-card"><div class="stat-top">Vendas realizadas <span class="stat-icon">↗</span></div><div class="stat-value">${dados.vendas.length}</div><div class="trend"><strong>↑ 18%</strong> vs. mês passado</div></div><div class="stat-card"><div class="stat-top">Faturamento total <span class="stat-icon">R$</span></div><div class="stat-value" style="font-size:22px">${moeda(faturamento)}</div><div class="trend"><strong>↑ 24%</strong> vs. mês passado</div></div></div>
    <div class="dashboard-grid"><div class="panel"><div class="panel-heading"><div><h3>Desempenho de vendas</h3><p>Faturamento dos últimos 7 dias</p></div><select class="filter-select"><option>Últimos 7 dias</option><option>Este mês</option></select></div><div class="chart-wrap"><div class="chart-grid"></div><div class="chart-y"><span>8k</span><span>6k</span><span>4k</span><span>2k</span><span>0</span></div><svg class="chart-svg" viewBox="0 0 600 180" preserveAspectRatio="none"><polyline points="0,150 100,112 200,125 300,72 400,91 500,26 600,55"></polyline><circle cx="500" cy="26" r="5"></circle></svg><div class="chart-labels"><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span><span>Dom</span></div></div></div><div class="panel"><div class="panel-heading"><div><h3>Estoque baixo</h3><p>Produtos que precisam de atenção</p></div><button class="text-button" onclick="mudarSecao('stock')">Ver estoque</button></div><div class="alert-list">${baixos.length ? baixos.map(produto => `<div class="alert-row">${avatarEmoji(produto.tema)}<div class="alert-info"><strong>${produto.nome}</strong><span>${produto.marca} · ${produto.armazenamento}</span></div><span class="stock-pill">${produto.estoque} un.</span></div>`).join('') : '<div class="empty-state">Nenhum produto em alerta.</div>'}</div></div></div>
    <div class="panel recent-panel"><div class="panel-heading"><div><h3>Vendas recentes</h3><p>Últimas movimentações realizadas</p></div><button class="text-button" onclick="mudarSecao('sales')">Ver todas</button></div>${tabelaVendas(recentes)}</div>`;
}
function tabelaVendas(vendas) { if (!vendas.length) return '<div class="empty-state"><strong>Nenhuma venda encontrada</strong>Registre a primeira venda para começar.</div>'; return `<div class="table-container"><table><thead><tr><th>Cliente</th><th>Produto</th><th>Data</th><th>Pagamento</th><th>Valor total</th><th>Status</th></tr></thead><tbody>${vendas.map(venda => { const cliente = clientePorId(venda.clienteId), produto = produtoPorId(venda.produtoId); return `<tr><td><div class="table-product"><div class="user-avatar small">${cliente?.nome.split(' ').map(p => p[0]).slice(0,2).join('')}</div><div><strong>${cliente?.nome || 'Cliente removido'}</strong><span>#${venda.id}</span></div></div></td><td>${produto?.nome || 'Produto removido'}</td><td>${dataFormatada(venda.data)}</td><td>${venda.pagamento}</td><td class="money">${moeda(venda.total)}</td><td><span class="status success">Concluída</span></td></tr>`; }).join('')}</tbody></table></div>`; }

function renderProdutos() { document.getElementById('productsSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">CATÁLOGO</p><h1>Produtos</h1><p>Gerencie os celulares disponíveis na sua loja.</p></div><button class="primary-button" onclick="abrirModal('product')">Cadastrar celular <span>+</span></button></div><div class="table-toolbar"><div class="search-box"><span>⌕</span><input id="productSearch" placeholder="Pesquisar por nome, marca ou modelo..." oninput="filtrarProdutos(this.value)"></div><select class="filter-select"><option>Todos os produtos</option><option>Estoque baixo</option></select></div><div id="productCards" class="products-grid">${cardsProdutos(dados.produtos)}</div>`; }
function cardsProdutos(produtos) { if (!produtos.length) return '<div class="empty-state"><strong>Nenhum celular encontrado</strong>Experimente outra busca.</div>'; return produtos.map(produto => `<article class="product-card">${productVisual(produto)}<div class="card-actions"><button title="Editar" onclick="abrirModal('product',${produto.id})">✎</button><button title="Excluir" onclick="excluirRegistro('produto',${produto.id})">×</button></div><div class="product-card-content"><h3>${produto.nome}</h3><p>${produto.marca} · ${produto.armazenamento} · ${produto.cor}</p><div class="product-meta"><strong>${moeda(produto.preco)}</strong><span class="stock-text ${produto.estoque <= 3 ? 'low' : ''}">${produto.estoque} em estoque</span></div></div></article>`).join(''); }
function filtrarProdutos(termo) { const busca = termo.toLowerCase(); document.getElementById('productCards').innerHTML = cardsProdutos(dados.produtos.filter(p => `${p.nome} ${p.marca} ${p.modelo}`.toLowerCase().includes(busca))); }

function renderClientes() { document.getElementById('clientsSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">RELACIONAMENTO</p><h1>Clientes</h1><p>Tenha seus clientes sempre organizados.</p></div><button class="primary-button" onclick="abrirModal('client')">Cadastrar cliente <span>+</span></button></div><div class="panel"><div class="table-toolbar"><div class="search-box"><span>⌕</span><input placeholder="Pesquisar por nome, CPF ou e-mail..." oninput="filtrarClientes(this.value)"></div><span class="status success">${dados.clientes.length} clientes ativos</span></div><div class="table-container" id="clientsTable">${tabelaClientes(dados.clientes)}</div></div>`; }
function tabelaClientes(clientes) { if (!clientes.length) return '<div class="empty-state"><strong>Nenhum cliente encontrado</strong></div>'; return `<table><thead><tr><th>Cliente</th><th>CPF</th><th>Telefone</th><th>E-mail</th><th>Endereço</th><th>Ações</th></tr></thead><tbody>${clientes.map(c => `<tr><td><div class="table-product"><div class="user-avatar small">${c.nome.split(' ').map(p => p[0]).slice(0,2).join('')}</div><strong>${c.nome}</strong></div></td><td>${c.cpf}</td><td>${c.telefone}</td><td>${c.email}</td><td>${c.endereco}</td><td><button class="action-button" onclick="abrirModal('client',${c.id})">✎</button><button class="action-button" onclick="excluirRegistro('cliente',${c.id})">×</button></td></tr>`).join('')}</tbody></table>`; }
function filtrarClientes(termo) { const busca = termo.toLowerCase(); document.getElementById('clientsTable').innerHTML = tabelaClientes(dados.clientes.filter(c => `${c.nome} ${c.cpf} ${c.email}`.toLowerCase().includes(busca))); }

function renderVendas() { document.getElementById('salesSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">OPERAÇÃO</p><h1>Vendas</h1><p>Registre e acompanhe todas as vendas da loja.</p></div><button class="primary-button" onclick="abrirModal('sale')">Registrar venda <span>+</span></button></div><div class="summary-strip"><div class="summary-item"><span>Vendas no período</span><strong>${dados.vendas.length}</strong></div><div class="summary-item"><span>Ticket médio</span><strong>${moeda(dados.vendas.length ? dados.vendas.reduce((s,v)=>s+v.total,0)/dados.vendas.length : 0)}</strong></div><div class="summary-item"><span>Produtos vendidos</span><strong>${dados.vendas.reduce((s,v)=>s+v.quantidade,0)}</strong></div></div><div class="panel"><div class="table-toolbar"><h3 style="font-family:'Space Grotesk';margin:0">Histórico de vendas</h3><select class="filter-select"><option>Todos os períodos</option><option>Este mês</option></select></div>${tabelaVendas([...dados.vendas].sort((a,b)=>new Date(b.data)-new Date(a.data)))}</div>`; }

function renderEstoque() { document.getElementById('stockSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">CONTROLE</p><h1>Estoque</h1><p>Monitore entradas, saídas e níveis de produtos.</p></div><button class="primary-button" onclick="abrirModal('movement')">Movimentar estoque <span>+</span></button></div><div class="summary-strip"><div class="summary-item"><span>Itens em estoque</span><strong>${dados.produtos.reduce((s,p)=>s+p.estoque,0)}</strong></div><div class="summary-item"><span>Produtos disponíveis</span><strong>${dados.produtos.filter(p=>p.estoque > 0).length}</strong></div><div class="summary-item"><span>Estoque baixo</span><strong style="color:var(--red)">${dados.produtos.filter(p=>p.estoque <= 3).length}</strong></div></div><div class="panel"><div class="table-toolbar"><h3 style="font-family:'Space Grotesk';margin:0">Visão geral do estoque</h3><div class="search-box"><span>⌕</span><input placeholder="Buscar produto..."></div></div><div class="table-container"><table><thead><tr><th>Produto</th><th>Marca / modelo</th><th>Preço unitário</th><th>Quantidade</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${dados.produtos.map(p=>`<tr><td><div class="table-product">${avatarEmoji(p.tema)}<strong>${p.nome}</strong></div></td><td>${p.marca} · ${p.modelo}</td><td class="money">${moeda(p.preco)}</td><td><strong>${p.estoque}</strong> un.</td><td><span class="status ${p.estoque<=3?'danger':'success'}">${p.estoque<=3?'Estoque baixo':'Disponível'}</span></td><td><button class="secondary-button" style="padding:7px 9px" onclick="abrirModal('movement',${p.id})">+ / −</button></td></tr>`).join('')}</tbody></table></div></div>`; }

function renderRelatorios() { const ranking = dados.produtos.map(p=>({...p, vendidos:dados.vendas.filter(v=>v.produtoId===p.id).reduce((s,v)=>s+v.quantidade,0)})).sort((a,b)=>b.vendidos-a.vendidos); const total = dados.vendas.reduce((s,v)=>s+v.total,0); document.getElementById('reportsSection').innerHTML = `<div class="page-heading"><div><p class="eyebrow">ANÁLISE</p><h1>Relatórios</h1><p>Indicadores para entender o desempenho da sua operação.</p></div><button class="secondary-button" onclick="mostrarToast('Relatório pronto','A versão para impressão foi preparada.')">⇩ Exportar relatório</button></div><div class="report-grid"><div class="panel"><div class="panel-heading"><div><h3>Produtos mais vendidos</h3><p>Quantidade de unidades vendidas</p></div></div><div class="bar-list">${ranking.map((p,i)=>`<div class="bar-item"><div><strong>${i+1}. ${p.nome}</strong><span>${p.vendidos} un.</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(8, p.vendidos / Math.max(1, ranking[0].vendidos) * 100)}%"></div></div></div>`).join('')}</div></div><div class="report-highlight"><p class="eyebrow">RESULTADO ACUMULADO</p><h3>Visão financeira</h3><p>O total vendido no histórico atual é calculado automaticamente a partir das vendas registradas.</p><strong>${moeda(total)}</strong></div><div class="panel"><div class="panel-heading"><div><h3>Estoque atual</h3><p>Valor estimado dos produtos em loja</p></div></div><div class="summary-item" style="border:0;padding:0"><span>Valor do inventário</span><strong>${moeda(dados.produtos.reduce((s,p)=>s+p.estoque*p.preco,0))}</strong></div></div></div>`; }

function abrirModal(tipo, id = null) { tipoModal = tipo; idEditando = id; const modal = document.getElementById('formModal'); const form = document.getElementById('recordForm'); const config = { product: ['PRODUTO', id ? 'Editar celular' : 'Novo celular'], client: ['CLIENTE', id ? 'Editar cliente' : 'Novo cliente'], sale: ['VENDA', 'Registrar nova venda'], movement: ['ESTOQUE', 'Movimentar estoque'] }[tipo]; document.getElementById('modalEyebrow').textContent = config[0]; document.getElementById('modalTitle').textContent = config[1]; form.innerHTML = tipo === 'product' ? formProduto(id) : tipo === 'client' ? formCliente(id) : tipo === 'sale' ? formVenda() : formMovimentacao(id); modal.classList.remove('hidden'); if (tipo === 'sale') atualizarTotalVenda(); }
function fecharModal() { document.getElementById('formModal').classList.add('hidden'); idEditando = null; tipoModal = ''; }
function campo(label, name, value='', type='text', extra='') { return `<label class="form-field"><span>${label}</span><input name="${name}" type="${type}" value="${value}" ${extra} required></label>`; }
function formProduto(id) { const p = id ? produtoPorId(id) : {}; return `<div class="form-grid">${campo('Nome do celular','nome',p.nome||'')}${campo('Marca','marca',p.marca||'')}${campo('Modelo','modelo',p.modelo||'')}${campo('Armazenamento','armazenamento',p.armazenamento||'')}${campo('Cor','cor',p.cor||'')}${campo('Preço','preco',p.preco||'', 'number','step="0.01" min="0"')}${campo('Quantidade em estoque','estoque',p.estoque??'', 'number','min="0"')}<label class="form-field"><span>Imagem (URL opcional)</span><input name="imagem" type="text" value="${p.imagem||''}"></label><div class="form-actions form-field full-field"><button type="button" class="secondary-button" onclick="fecharModal()">Cancelar</button><button class="primary-button" type="submit">Salvar produto</button></div></div>`; }
function formCliente(id) { const c = id ? clientePorId(id) : {}; return `<div class="form-grid">${campo('Nome completo','nome',c.nome||'')}${campo('CPF','cpf',c.cpf||'')}${campo('Telefone','telefone',c.telefone||'')}${campo('E-mail','email',c.email||'','email')}${campo('Endereço','endereco',c.endereco||'','text','class="full-field"') }<div class="form-actions form-field full-field"><button type="button" class="secondary-button" onclick="fecharModal()">Cancelar</button><button class="primary-button" type="submit">Salvar cliente</button></div></div>`; }
function formVenda() { return `<div class="form-grid">${campoSelect('Cliente','clienteId',dados.clientes.map(c=>[c.id,c.nome]))}${campoSelect('Celular','produtoId',dados.produtos.filter(p=>p.estoque>0).map(p=>[p.id,`${p.nome} · ${moeda(p.preco)}`]),'atualizarTotalVenda()')}${campo('Quantidade','quantidade',1,'number','min="1" oninput="atualizarTotalVenda()"')}${campoSelect('Forma de pagamento','pagamento',[['PIX','PIX'],['Cartão de crédito','Cartão de crédito'],['Cartão de débito','Cartão de débito'],['Dinheiro','Dinheiro']])}<div class="summary-item full-field"><span>Valor total da venda</span><strong id="saleTotal">R$ 0,00</strong></div><div class="form-actions form-field full-field"><button type="button" class="secondary-button" onclick="fecharModal()">Cancelar</button><button class="primary-button" type="submit">Confirmar venda</button></div></div>`; }
function campoSelect(label,name,options,onchange='',selectedValue='') { return `<label class="form-field"><span>${label}</span><select name="${name}" ${onchange ? `onchange="${onchange}"` : ''} required>${options.map(o=>`<option value="${o[0]}" ${String(o[0]) === String(selectedValue) ? 'selected' : ''}>${o[1]}</option>`).join('')}</select></label>`; }
function formMovimentacao(id) { return `<div class="form-grid">${campoSelect('Celular','produtoId',dados.produtos.map(p=>[p.id,`${p.nome} · saldo ${p.estoque}`]),'',id)}${campoSelect('Tipo de movimentação','tipo',[['entrada','Entrada de produtos'],['saida','Saída de produtos']])}${campo('Quantidade','quantidade',1,'number','min="1"')}${campo('Observação','observacao','','text','') }<div class="form-actions form-field full-field"><button type="button" class="secondary-button" onclick="fecharModal()">Cancelar</button><button class="primary-button" type="submit">Salvar movimentação</button></div></div>`; }
function atualizarTotalVenda() { const form = document.getElementById('recordForm'); if (!form || tipoModal !== 'sale') return; const p = produtoPorId(form.produtoId.value); const total = p ? p.preco * Number(form.quantidade.value || 0) : 0; const target = document.getElementById('saleTotal'); if (target) target.textContent = moeda(total); }
function processarFormulario(event) { event.preventDefault(); const form = new FormData(event.target); const valores = Object.fromEntries(form.entries()); if (tipoModal === 'product') { const produto = { id: idEditando || Date.now(), nome: valores.nome, marca: valores.marca, modelo: valores.modelo, armazenamento: valores.armazenamento, cor: valores.cor, preco: Number(valores.preco), estoque: Number(valores.estoque), imagem: valores.imagem, emoji:'▰', tema: ['blue','gold','black'][dados.produtos.length % 3] }; if (idEditando) dados.produtos = dados.produtos.map(p => p.id === idEditando ? {...p,...produto} : p); else dados.produtos.push(produto); mostrarToast('Produto salvo','O catálogo foi atualizado com sucesso.'); } else if (tipoModal === 'client') { const cliente = { id: idEditando || Date.now(), ...valores }; if (idEditando) dados.clientes = dados.clientes.map(c => c.id === idEditando ? cliente : c); else dados.clientes.push(cliente); mostrarToast('Cliente salvo','O cadastro foi atualizado com sucesso.'); } else if (tipoModal === 'sale') { const p = produtoPorId(valores.produtoId); const quantidade = Number(valores.quantidade); if (!p || quantidade > p.estoque) return mostrarToast('Estoque insuficiente','Reduza a quantidade ou faça uma entrada.'); p.estoque -= quantidade; dados.vendas.push({ id: Date.now(), clienteId: Number(valores.clienteId), produtoId: Number(valores.produtoId), quantidade, total: p.preco * quantidade, pagamento: valores.pagamento, data: new Date().toISOString() }); mostrarToast('Venda registrada','Estoque atualizado automaticamente.'); } else { const p = produtoPorId(valores.produtoId); const quantidade = Number(valores.quantidade); if (valores.tipo === 'saida' && quantidade > p.estoque) return mostrarToast('Estoque insuficiente','A saída não pode ser maior que o saldo atual.'); p.estoque += valores.tipo === 'entrada' ? quantidade : -quantidade; mostrarToast('Estoque atualizado','A movimentação foi registrada.'); } salvarDados(); fecharModal(); renderizar(); }
function excluirRegistro(tipo, id) { const nome = tipo === 'produto' ? 'produto' : 'cliente'; if (!confirm(`Deseja realmente excluir este ${nome}?`)) return; if (tipo === 'produto') dados.produtos = dados.produtos.filter(p => p.id !== id); else dados.clientes = dados.clientes.filter(c => c.id !== id); salvarDados(); renderizar(); mostrarToast('Registro excluído',`O ${nome} foi removido.`); }
function mudarSecao(secao) { secaoAtual = secao; renderizar(); window.scrollTo({top:0,behavior:'smooth'}); document.getElementById('sidebar').classList.remove('open'); }

document.addEventListener('DOMContentLoaded', async () => { document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => mudarSecao(item.dataset.section))); document.getElementById('menuButton').addEventListener('click', () => document.getElementById('sidebar').classList.toggle('open')); document.getElementById('closeFormModal').addEventListener('click', fecharModal); document.getElementById('recordForm').addEventListener('submit', processarFormulario); document.getElementById('togglePassword').addEventListener('click', () => { const input = document.querySelector('[name="password"]'); input.type = input.type === 'password' ? 'text' : 'password'; }); document.getElementById('loginForm').addEventListener('submit', event => { event.preventDefault(); document.getElementById('loginModal').classList.add('hidden'); mostrarToast('Login realizado','Bem-vindo ao painel CellTech.'); }); document.getElementById('logoutButton').addEventListener('click', () => document.getElementById('loginModal').classList.remove('hidden')); await carregarDadosDoBanco(); renderizar(); });
